# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Fall 2026'
tagline:          'A workshop for GAP developers and users'
description:      '28 Sept - 2 Oct 2026'
location:         'RWTH Aachen, Germany'
url:              https://www.gapdays.de
baseurl:          /gapdays2026-fall
email:            gapdays@gap-system.org

exclude: 
    - "LICENSE.hyde.md"
    - "README.hyde.md"
    - "TODO.md"
    - "program.aux"
    - "program.log"
    - "program.out"
    - "program.tex"
    - "misc"
    - "welcome"
